"""empty message

Revision ID: b5e516babef3
Revises: 
Create Date: 2020-02-06 15:34:27.351959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e516babef3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Applicant', sa.Column('group_title', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'Applicant', type_='foreignkey')
    op.create_foreign_key(None, 'Applicant', 'Group', ['group_title'], ['title'])
    op.drop_column('Applicant', 'group_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Applicant', sa.Column('group_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'Applicant', type_='foreignkey')
    op.create_foreign_key(None, 'Applicant', 'Group', ['group_id'], ['id'])
    op.drop_column('Applicant', 'group_title')
    # ### end Alembic commands ###
